In [1]:
#defining three random arrays, a one-dimensional, two-dimensional, and three-dimensional 
#array using NumPy's random number generator

In [2]:
import numpy as np
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [3]:
#attributes: 
#ndim (the number of dimensions)
#shape (the size of each dimension)
#size (the total size of the array)

In [4]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [5]:
#other useful attribute is the dtype, the data type of the array
print("dtype:", x3.dtype)

dtype: int64


In [6]:
#itemsize lists the size (in bytes) of each array element 
print("itemsize:", x3.itemsize, "bytes")

itemsize: 8 bytes


In [7]:
#nbytes lists the total size (in bytes) of the array
print("nbytes:", x3.nbytes, "bytes")

nbytes: 480 bytes


In [8]:
#Array Indexing: Accessing Single Elements

In [9]:
x1

array([5, 0, 3, 3, 7, 9])

In [10]:
#position values can be accessed by specifying the index in [brackets]
x1[0]

5

In [11]:
#to index from the end of the array, you can use negative indices
x1[-1]
#the count is from -1 to -n

9

In [12]:
#multi-dimensional array

In [13]:
 #items can be accessed using a comma-separated tuple of indices
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
x2[0, 0]

3

In [15]:
#or
x2[-3, -4]

3

In [16]:
# Array Slicing: Accessing Subarrays
#to access a slice of an array x:
# x[start:stop:step]
# if any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1

In [17]:
## One-dimensional subarrays

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [20]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

NameError: name 'f' is not defined