In [1]:
import numpy as np

In [2]:
#Python lists can be simple as follow

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
#But we can even create heterogeneous lists:

In [5]:
L3 = [True, "2", 3.0, 4]
L3

[True, '2', 3.0, 4]

In [7]:
#We can check the types inside a list as follow:
[type(item) for item in L3]

[bool, str, float, int]

In [9]:
#arrays using python default

In [11]:
import array
L = list(range(10))
A = array.array('i', L) #where i indicates integer type
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#np.array helps us to create arrays from Python lists

In [13]:
# integer array:
np.array([1, 4, 2, 5, 3])
#unlike Python lists, NumPy is constrained to arrays 
#that all contain the same type

array([1, 4, 2, 5, 3])

In [14]:
#If types do not match, NumPy will upcast if possible 
#Here, integers are up-cast to floating point
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [15]:
#To explicitly set the data type, we can use dtype
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [16]:
#Unlike Python lists, NumPy arrays can explicitly be multi-dimensional
# nested lists result in multi-dimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [17]:
#it is more efficient to create arrays from scratch using 
#routines built into NumPy

In [21]:
#examples:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [26]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 5
# (this is similar to the built-in range() function)
np.arange(0, 20, 5)

array([ 0,  5, 10, 15])

In [27]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.86938149,  0.61524956, -0.07925043],
       [ 0.15708758, -1.915556  ,  0.59572511],
       [ 0.78104204, -0.98703161, -0.08763523]])